[profile.default]
src = 'packages/contracts/src'
test = 'packages/contracts/test'
out = 'out'
libs = ["packages/contracts/node_modules", "packages/contracts/lib"]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config