#!/usr/bin/env sh

pnpm install
pnpm clean
pnpm generate
pnpm build

(cd packages/contracts && pnpm version patch)
(cd packages/sdk && pnpm version patch)

pnpm --no-git-checks --filter "@mintdrop/*" publish
